# Generated by Django 4.2.6 on 2023-11-14 07:35

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_bom_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('quote', models.IntegerField()),
                ('adjust_service', models.FloatField()),
                ('adjust_bom', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('list', models.IntegerField()),
                ('cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Project Management', 'Project Management'), ('Engineering (In House)', 'Engineering (In House)'), ('Engineering (On Site)', 'Engineering (On Site)'), ('Programming (In House)', 'Programming (In House)'), ('Programming (On Site)', 'Programming (On Site)'), ('Shipping/Procurement', 'Shipping/Procurement'), ('Admin', 'Admin')], max_length=100)),
                ('hours_estimated', models.IntegerField()),
                ('hours_worked', models.IntegerField()),
                ('rate_list', models.IntegerField(blank=True, null=True)),
                ('rate_cost', models.IntegerField(blank=True, null=True)),
                ('travel_actual', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project_service_category', to='budgetTool.servicecategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_service', to='budgetTool.project')),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CUSTOM HARDWARE', 'Custom Hardware'), ('UMA SOLUTION', 'UMA Solution'), ('CONTROLS', 'Controls'), ('SOFTWARE', 'Software'), ('PROTECTION PLANS', 'Protection Plans')], max_length=100)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('estimate_cost', models.IntegerField()),
                ('sales_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=300)),
                ('actual_cost', models.IntegerField()),
                ('Responsible', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bom', to='budgetTool.project')),
            ],
        ),
    ]
