# Generated by Django 4.2.6 on 2023-12-20 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_bom_cost', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BOMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('quote_BOM', models.IntegerField()),
                ('quote_Service', models.IntegerField()),
                ('adjust_Service', models.FloatField()),
                ('adjust_BOM', models.FloatField()),
                ('travel_weekly', models.IntegerField()),
                ('isTemplate', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RateTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100)),
                ('list', models.FloatField()),
                ('cost', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RateTableCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('base', models.IntegerField()),
                ('y1', models.IntegerField(blank=True, null=True)),
                ('y2', models.IntegerField(blank=True, null=True)),
                ('y3', models.IntegerField(blank=True, null=True)),
                ('y4', models.IntegerField(blank=True, null=True)),
                ('labor_cost', models.IntegerField(blank=True, null=True)),
                ('labor_in_house', models.FloatField(default=165)),
                ('labor_on_site', models.FloatField(default=287.5)),
                ('employee', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=100)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('hours_estimated', models.IntegerField()),
                ('hours_worked', models.IntegerField(blank=True)),
                ('rate_list', models.FloatField(blank=True, default=0)),
                ('rate_cost', models.FloatField(blank=True, default=0)),
                ('travel_actual', models.IntegerField(blank=True)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('isOnSite', models.BooleanField(default=False)),
                ('hours_adjusted', models.FloatField(default=0)),
                ('travel_estimate', models.FloatField(default=0)),
                ('sub_total_list', models.IntegerField(default=0)),
                ('sub_total_adjusted_list', models.IntegerField(default=0)),
                ('sub_total_cost_est', models.IntegerField(default=0)),
                ('sub_total_adjusted_cost_est', models.IntegerField(default=0)),
                ('cost_actual', models.IntegerField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_service_category', to='budgetTool.servicecategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_service', to='budgetTool.project')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_service_type', to='budgetTool.ratetablecost')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('list', models.FloatField()),
                ('margin', models.FloatField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=1000, null=True)),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vendor', to='budgetTool.vendor')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_level', to='budgetTool.ratetablecost')),
            ],
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, default=1000)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('estimate_cost', models.IntegerField()),
                ('sales_price', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(blank=True, max_length=300)),
                ('actual_cost', models.FloatField()),
                ('Responsible', models.CharField(blank=True, max_length=300)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('bom_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_BOM_category', to='budgetTool.bomcategory')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_bom', to='budgetTool.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
