# Generated by Django 4.2.6 on 2023-10-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='quote',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
    ]
