# Generated by Django 4.2.6 on 2023-11-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='Notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='Responsible',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
