# Generated by Django 4.2.6 on 2023-12-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='actual_bom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='actual_service',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_adjusted_bom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_adjusted_service',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_est_bom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='cost_est_service',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='list_adjusted_bom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='list_adjusted_service',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='list_bom',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='list_service',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
