# Generated by Django 4.2.6 on 2023-12-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0002_project_actual_bom_project_actual_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='sales_price',
            field=models.IntegerField(default=0),
        ),
    ]
