# Generated by Django 4.2.6 on 2023-11-01 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0002_project_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='name',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(default='pro', max_length=100),
            preserve_default=False,
        ),
    ]
