# Generated by Django 4.2.6 on 2023-11-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0002_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='travel_weekly',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
