# Generated by Django 4.2.6 on 2023-11-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0002_billofmaterials_notes_billofmaterials_responsible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='index',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_one',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_three',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_two',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='supplier',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='vender_one',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='vender_three',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='vender_two',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
