# Generated by Django 4.2.6 on 2023-11-07 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0003_alter_billofmaterials_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_one',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_three',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='quote_two',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='billofmaterials',
            name='supplier',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
