# Generated by Django 4.2.6 on 2023-11-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0003_project_travel_weekly'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hours_adjusted',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='travel_estimate',
            field=models.FloatField(default=0),
        ),
    ]
