# Generated by Django 4.2.6 on 2023-12-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0004_alter_billofmaterials_sales_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='sales_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
