# Generated by Django 4.2.6 on 2023-11-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0004_alter_billofmaterials_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='supplier',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
