# Generated by Django 4.2.6 on 2023-11-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0004_service_hours_adjusted_service_travel_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='cost_actual',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sub_total_adjusted_cost_est',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sub_total_adjusted_list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sub_total_cost_est',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='sub_total_list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
