# Generated by Django 4.2.6 on 2023-12-28 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0005_alter_billofmaterials_sales_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_est', models.FloatField()),
                ('cost_adjusted', models.FloatField()),
                ('list', models.FloatField()),
                ('list_adjusted', models.FloatField()),
                ('actual', models.FloatField()),
                ('list_margin', models.FloatField()),
                ('list_adjusted_margin', models.FloatField()),
                ('quoted_margin', models.FloatField()),
                ('actual_margin', models.FloatField()),
            ],
        ),
    ]
