# Generated by Django 4.2.6 on 2023-11-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0005_alter_billofmaterials_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='total_service_cost',
        ),
        migrations.AddField(
            model_name='service',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('GENERAL PROJECT', 'GENERAL PROJECT'), ('HARDWARE DEVELOPMENT', 'HARDWARE DEVELOPMENT'), ('SOFTWARE DEVELOPMENT', 'SOFTWARE DEVELOPMENT'), ('IMPLEMENTATION ', 'IMPLEMENTATION '), ('FACTORY ACCEPTANCE TEST', 'FACTORY ACCEPTANCE TEST'), ('SHIPPING', 'SHIPPING'), ('INSTALLATION', 'INSTALLATION'), ('SITE ACCEPTANCE TEST', 'SITE ACCEPTANCE TEST'), ('TRAINING', 'TRAINING')], max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(choices=[('Project Management', 'Project Management'), ('Engineering (In House)', 'Engineering (In House)'), ('Engineering (On Site)', 'Engineering (On Site)'), ('Programming (In House)', 'Programming (In House)'), ('Programming (On Site)', 'Programming (On Site)'), ('Shipping/Procurement', 'Shipping/Procurement'), ('Admin', 'Admin')], max_length=100),
        ),
        migrations.DeleteModel(
            name='CustomHardware',
        ),
    ]
