# Generated by Django 4.2.6 on 2023-11-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0005_service_cost_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost_actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_total_adjusted_cost_est',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_total_adjusted_list',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_total_cost_est',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='sub_total_list',
            field=models.IntegerField(default=0),
        ),
    ]
