# Generated by Django 4.2.6 on 2023-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0006_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Margins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('margin_est_bom', models.FloatField()),
                ('margin_est_service', models.FloatField()),
                ('margin_adjusted_bom', models.FloatField()),
                ('margin_adjusted_service', models.FloatField()),
                ('margin_actual_bom', models.FloatField()),
                ('margin_actual_service', models.FloatField()),
                ('margin_quoted_bom', models.FloatField()),
            ],
        ),
    ]
