# Generated by Django 4.2.6 on 2023-11-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0006_remove_service_total_service_cost_service_index_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billofmaterials',
            old_name='Notes',
            new_name='notes',
        ),
        migrations.AddField(
            model_name='project',
            name='adjust_bom',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='adjust_service',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
