# Generated by Django 4.2.6 on 2023-11-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0006_alter_service_cost_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate_cost',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_list',
            field=models.FloatField(default=-1),
        ),
    ]
