# Generated by Django 4.2.6 on 2023-12-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0007_margins'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='hours',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='hours_adjusted',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
