# Generated by Django 4.2.6 on 2023-11-15 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0007_alter_service_rate_cost_alter_service_rate_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOMCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='category',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='bom_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_BOM_category', to='budgetTool.bomcategory'),
        ),
    ]
