# Generated by Django 4.2.6 on 2023-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0008_bomcategory_remove_billofmaterials_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='adjust_bom',
            new_name='adjust_BOM',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='adjust_service',
            new_name='adjust_Service',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='quote',
            new_name='quote_BOM',
        ),
        migrations.AddField(
            model_name='project',
            name='quote_Service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
