# Generated by Django 4.2.6 on 2023-11-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0009_alter_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='billofmaterials',
            name='estimate_cost',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='sales_price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='rate_cost',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='rate_list',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
