# Generated by Django 4.2.6 on 2024-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0009_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='index',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
