# Generated by Django 4.2.6 on 2023-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0009_rename_adjust_bom_project_adjust_bom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billofmaterials',
            name='actual_cost',
            field=models.FloatField(),
        ),
    ]
