# Generated by Django 4.2.6 on 2024-01-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0010_alter_profile_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='index',
            new_name='Product_Price_index',
        ),
        migrations.AddField(
            model_name='profile',
            name='RateTable_index',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bom_index',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_index',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
