# Generated by Django 4.2.6 on 2023-11-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0010_alter_billofmaterials_actual_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetable',
            name='cost',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ratetable',
            name='list',
            field=models.FloatField(),
        ),
    ]
