# Generated by Django 4.2.6 on 2023-11-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0010_billofmaterials_estimate_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='adjust_bom',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='adjust_service',
            field=models.FloatField(),
        ),
    ]
