# Generated by Django 4.2.6 on 2024-02-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0011_rename_index_profile_product_price_index_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hours_estimated',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='hours_worked',
            field=models.FloatField(blank=True),
        ),
    ]
