# Generated by Django 4.2.6 on 2023-11-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0011_alter_project_adjust_bom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_list',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
