# Generated by Django 4.2.6 on 2024-02-13 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0012_alter_service_hours_estimated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='cost_actual',
            field=models.FloatField(default=0),
        ),
    ]
