# Generated by Django 4.2.6 on 2023-12-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0012_alter_project_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='billofmaterials',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='order',
            field=models.IntegerField(blank=True, default=1000),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
