# Generated by Django 4.2.6 on 2023-12-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0013_alter_billofmaterials_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bomcategory',
            options={'ordering': ['index']},
        ),
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['index']},
        ),
    ]
