# Generated by Django 4.2.6 on 2023-12-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0014_alter_bomcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='service',
            name='isOnSite',
            field=models.BooleanField(default=False),
        ),
    ]
