# Generated by Django 4.2.6 on 2023-12-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0015_alter_project_options_service_isonsite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_list',
            field=models.FloatField(default=0),
        ),
    ]
