# Generated by Django 4.2.6 on 2023-12-12 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0016_alter_service_rate_cost_alter_service_rate_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('base', models.IntegerField()),
                ('y1', models.IntegerField()),
                ('y2', models.IntegerField()),
                ('y3', models.IntegerField()),
                ('y4', models.IntegerField()),
                ('labor_cost', models.IntegerField()),
                ('labor_in_house', models.IntegerField()),
                ('labor_on_site', models.IntegerField()),
                ('names', models.CharField(max_length=200)),
                ('total_lobar_cost', models.IntegerField()),
            ],
        ),
    ]
