# Generated by Django 4.2.6 on 2023-12-12 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0017_labor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labor',
            old_name='names',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='labor',
            name='total_lobar_cost',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_level', to='budgetTool.labor')),
            ],
        ),
    ]
