# Generated by Django 4.2.6 on 2023-12-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0018_rename_names_labor_employee_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Labor',
            new_name='RateTableCost',
        ),
    ]
