# Generated by Django 4.2.6 on 2023-12-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0019_rename_labor_ratetablecost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetablecost',
            name='labor_cost',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='labor_in_house',
            field=models.FloatField(default=165),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='labor_on_site',
            field=models.FloatField(default=287.5),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y2',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y3',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y4',
            field=models.IntegerField(blank=True),
        ),
    ]
