# Generated by Django 4.2.6 on 2023-12-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0020_alter_ratetablecost_labor_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetablecost',
            name='labor_cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ratetablecost',
            name='y4',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
