# Generated by Django 4.2.6 on 2023-12-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0021_alter_ratetablecost_labor_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratetablecost',
            name='employee',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
