# Generated by Django 4.2.6 on 2023-12-13 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0022_alter_ratetablecost_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.AlterModelOptions(
            name='ratetablecost',
            options={'ordering': ['name']},
        ),
        migrations.CreateModel(
            name='Product_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('item', models.CharField(max_length=100)),
                ('cost', models.FloatField()),
                ('list', models.FloatField()),
                ('margin', models.FloatField()),
                ('note', models.CharField(max_length=1000)),
                ('price', models.FloatField()),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_vendor', to='budgetTool.vendor')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
