# Generated by Django 4.2.6 on 2023-12-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0023_vendor_alter_ratetablecost_options_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_price',
            name='price',
        ),
        migrations.AlterField(
            model_name='product_price',
            name='index',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='margin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product_price',
            name='note',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
