# Generated by Django 4.2.6 on 2023-12-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0024_remove_product_price_price_alter_product_price_index_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_price',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='ratetablecost',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='ratetablecost',
            name='order',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
