# Generated by Django 4.2.6 on 2023-12-14 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0025_alter_product_price_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratetablecost',
            options={'ordering': ['order']},
        ),
        migrations.AlterField(
            model_name='vendor',
            name='index',
            field=models.IntegerField(default=100),
        ),
    ]
