# Generated by Django 4.2.6 on 2023-12-15 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0026_alter_ratetablecost_options_alter_vendor_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='isTemplate',
            field=models.BooleanField(default=False),
        ),
    ]
