# Generated by Django 4.2.6 on 2023-12-15 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0027_project_istemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='isTemplate',
            field=models.BooleanField(default=True),
        ),
    ]
