# Generated by Django 4.2.6 on 2023-12-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0028_alter_project_istemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hours_worked',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='travel_actual',
            field=models.IntegerField(blank=True),
        ),
    ]
