# Generated by Django 4.2.6 on 2023-12-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0029_alter_service_hours_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='hours_worked',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='travel_actual',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
