# Generated by Django 4.2.6 on 2023-12-16 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0031_alter_service_hours_worked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_service_type', to='budgetTool.ratetablecost'),
        ),
    ]
