# Generated by Django 4.2.6 on 2023-12-16 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0032_alter_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rate_cost',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='service',
            name='rate_list',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
