# Generated by Django 4.2.6 on 2023-12-17 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetTool', '0033_alter_service_rate_cost_alter_service_rate_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_price',
            name='index',
        ),
        migrations.AddField(
            model_name='product_price',
            name='order',
            field=models.IntegerField(blank=True, default=1000),
        ),
    ]
